site_name: Droughtbox
##site_url: https://ecamo19.github.io/gsoc2022_web/

theme:
  palette:
    primary: custom

    extra_css:
      - stylesheets/extra.css
  #logo: images/favicon2.png
  #favicon: images/favicon3.png

  # pip install mkdocs-material
  #name: material


  #features:
  #  - navigation.tabs
  #  - navigation.sections
  #  - toc.integrate
  #  - navigation.top
  # - search.suggest
  #  - search.highlight
  #  - content.tabs.link
  #  - content.code.annotation
  #  - content.code.copy 
  
  

  #palette:
  #  - scheme: default
  #    primary: green
  #    accent: blue
  #    toggle:
  #      icon: material/toggle-switch-off-outline 
  #      name: Switch to dark mode
  #  - scheme: slate 
  #    toggle:
  #      icon: material/toggle-switch
  #      name: Switch to light mode    
  #    primary: teal
  #    accent: lime

  

# pip install pillow cairosvg
#plugins:
#    - social

#extra:
#    social:
#      - icon: fontawesome/brands/github-alt
#        link: https://github.com/ecamo19
#      - icon: fontawesome/brands/twitter
#        link: https://twitter.com/ecamo19
      ##- icon: fontawesome/brands/linkedin
        ##link: https://www.linkedin.com/in/willettjames/
  
  
